name: Pipeline UI check
description: Composite actions for pipeline ui

inputs:
  base-ref:
    required: true
    description: Reference to base github branch

runs:
  using: composite
  steps:
    - name: Check if pipeline ui has changed
      id: is_pipeline_ui_changed
      uses: ./.github/actions/detect-directory-changes
      with:
        directory-path: pipeline-ui
        base-ref: ${{ inputs.base-ref }}
    - name: Set up Node
      if: steps.is_pipeline_ui_changed.outputs.is_changed == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: "22"
    - name: Lint UI
      shell: bash
      run: |
        if ${{steps.is_pipeline_ui_changed.outputs.is_changed}}; then
          echo "Directory contents have changed. Proceeding with subsequent checks"

          cd pipeline-ui
          npm install # TODO: use npm ci and introduce package-lock.json
          npm run lint
        else
          echo "Directory contents are unchanged. Skipping subsequent checks"
        fi
        