FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY pipeline/target/pipeline-0.0.1-SNAPSHOT.jar app.jar
COPY pipeline/target/agents/opentelemetry-javaagent.jar otel-agent.jar
EXPOSE 8080
ENTRYPOINT ["java", "-javaagent:otel-agent.jar", "-jar", "app.jar"]
