version: '3'

volumes:
  prometheus_data:
  loki_data:
  grafana_data:

services:
  alloy:
    image: grafana/alloy:v1.7.5
    ports:
      - 12345:12345
      - 4317:4317
      - 4318:4318
    volumes:
      - ${MONITORING_STACK_DIR:-.}/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki
    networks:
      - loki
      - prometheus
  loki:
    image: grafana/loki:3.4.2
    ports:
      - "3100:3100"
    volumes:
      - ${MONITORING_STACK_DIR:-.}/loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --web.enable-lifecycle
    volumes:
      - ${MONITORING_STACK_DIR:-.}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${MONITORING_STACK_DIR:-.}/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus_data:/prometheus
    networks:
      - prometheus
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    command:
      - --config.file=/etc/alertmanager/alerts.yml
    volumes:
      - ${MONITORING_STACK_DIR:-.}/alertmanager/alerts.yml:/etc/alertmanager/alerts.yml
    networks:
      - prometheus
    
  grafana:
    image: grafana/grafana:11.6.0
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=grafanaManagedRecordingRules
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app
    ports:
      - 3000:3000/tcp
    volumes:
      - ${MONITORING_STACK_DIR:-.}/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana_data:/var/lib/grafana
    networks:
      - prometheus
      - loki

networks:
    loki:
      name: autobuild_loki
    prometheus:
      name: autobuild_prometheus