name: Detect Directory Changes
description: Composite actions for detecting any changes to the given directory compared to main branch

inputs:
  base-ref:
    required: true
    description: Reference to base github branch
  directory-path:
    required: true
    description: Path to the directory to compare against main

runs:
  using: composite
  steps:
    - name: Check diff
      id: check-diff
      shell: bash
      run: |
        echo 'Checking if contents of ${{inputs.directory-path}} has changed'

        git fetch origin ${{ inputs.base-ref }}

        if git diff --name-only origin/${{ inputs.base-ref }} | grep "^${{ inputs.directory-path }}/"; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "${{ inputs.directory_path }} directory contents have changed!"
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "${{ inputs.directory_path }} directory contents are unchanged"
        fi

outputs:
  is_changed:
    value: ${{steps.check-diff.outputs.changed}}
    description: Value to indicate if directory content has changed or not.
