name: OpenAPI contract violation check
description: Composite actions for detecting if OpenAPI docs are not upto date.

inputs:
  base-ref:
    required: true
    description: Reference to base github branch
  has-pipeline-validations-executed:
    required: true
    description: Boolean detector to denote if pipeline-validations have been executed or not.

runs:
  using: composite
  steps:
    - name: OpenAPI docs changes
      id: is-openapi-docs-changed
      uses: ./.github/actions/detect-directory-changes
      with:
        base-ref: ${{inputs.base-ref}}
        directory-path: apis/openapi-spec
    - name: Violation Check
      shell: bash
      run: |
        echo "Checking if OpenAPI contracts has been violated"
        if ! git diff --quiet HEAD -- apis/openapi-spec; then
          echo "OpenAPI doc changes are uncommited. Please commit changes under /apis/openapi-doc."
          exit 1
        fi

        if [[ "${{inputs.has-pipeline-validations-executed}}" == "false" && "${{ steps.is-openapi-docs-changed.outputs.is_changed }}" == "true" ]]; then
          echo "Manual edit of OpenAPI docs are detected. Files under /apis/openapi-doc are to be strictly autogenerated. Consider generating the files and commit those."
          exit 1
        fi

        echo "OpenAPI docs are consistent."
