# TODO: Deprecate it and move it into one application.yaml

spring:
  datasource:
    url: jdbc:h2:mem:demodb
    driverClassName: org.h2.Driver
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/SpringBootRealm
          jwk-set-uri: http://localhost:8180/realms/SpringBootRealm/protocol/openid-connect/certs

logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
